// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Docs",
    columns: [
      { name: "user_id", type: "string" },
      { name: "docs_id", type: "string" },
      { name: "file_url", type: "string" },
      { name: "index_status", type: "string" },
      { name: "file_name", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Docs = InferredTypes["Docs"];
export type DocsRecord = Docs & XataRecord;

export type DatabaseSchema = {
  Docs: DocsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://satish-s-workspace-6midd6.us-east-1.xata.sh/db/docchat",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
